/*==============================================================================
                        BOOK STORE MANAGEMENT SYSTEM
                              SQL PROJECT
==============================================================================*/


/*==============================================================================
SECTION 1 : CREATE TABLES
==============================================================================*/

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS BOOKS;


-- CREATE BOOKS TABLE
CREATE TABLE BOOKS (
	BOOK_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100),
	AUTHOR VARCHAR(100),
	GENRE VARCHAR(50),
	PUBLISHED_YEAR INT,
	PRICE NUMERIC(10, 2),
	STOCK INT
);


-- CREATE CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100),
	EMAIL VARCHAR(50),
	PHONE VARCHAR(15),
	CITY VARCHAR(50),
	COUNTRY VARCHAR(150)
);


-- CREATE ORDERS TABLE
CREATE TABLE ORDERS (
	ORDER_ID SERIAL PRIMARY KEY,
	CUSTOMER_ID INT REFERENCES CUSTOMERS (CUSTOMER_ID),
	BOOK_ID INT REFERENCES BOOKS (BOOK_ID),
	ORDER_DATE DATE,
	QUANTITY INT,
	TOTAL_AMOUNT NUMERIC(10, 2)
);



/*==============================================================================
SECTION 2 : IMPORT DATA
==============================================================================*/

COPY BOOKS (
	BOOK_ID,
	TITLE,
	AUTHOR,
	GENRE,
	PUBLISHED_YEAR,
	PRICE,
	STOCK
)
FROM
	'C:\Users\heman\Downloads\sql project\Books.csv'
DELIMITER ','
CSV HEADER;


COPY CUSTOMERS (
	CUSTOMER_ID,
	NAME,
	EMAIL,
	PHONE,
	CITY,
	COUNTRY
)
FROM
	'C:\Users\heman\Downloads\sql project\Customers.csv'
DELIMITER ','
CSV HEADER;


COPY ORDERS (
	ORDER_ID,
	CUSTOMER_ID,
	BOOK_ID,
	ORDER_DATE,
	QUANTITY,
	TOTAL_AMOUNT
)
FROM
	'C:\Users\heman\Downloads\sql project\Orders.csv'
DELIMITER ','
CSV HEADER;


-- VERIFY IMPORTS

SELECT * FROM BOOKS;

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;



/*==============================================================================
SECTION 3 : BASIC SQL QUERIES
==============================================================================*/


-- QUERY 1 : RETRIEVE ALL FICTION BOOKS

SELECT
	*
FROM
	BOOKS
WHERE
	GENRE = 'Fiction';


-- QUERY 2 : FIND BOOKS PUBLISHED AFTER 1950

SELECT
	*
FROM
	BOOKS
WHERE
	PUBLISHED_YEAR > 1950;


-- QUERY 3 : LIST ALL CUSTOMERS FROM CANADA

SELECT
	*
FROM
	CUSTOMERS
WHERE
	COUNTRY = 'Canada';


-- QUERY 4 : SHOW ORDERS PLACED IN NOVEMBER 2023

SELECT
	*
FROM
	ORDERS
WHERE
	ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';


-- QUERY 5 : CALCULATE TOTAL STOCK AVAILABLE

SELECT
	SUM(STOCK) AS TOTAL_BOOKS
FROM
	BOOKS;


-- QUERY 6 : FIND THE MOST EXPENSIVE BOOK

SELECT
	*
FROM
	BOOKS
WHERE
	PRICE = (
		SELECT
			MAX(PRICE)
		FROM
			BOOKS
	);


-- ALTERNATE SOLUTION FOR QUERY 6

SELECT
	*
FROM
	BOOKS
ORDER BY
	PRICE DESC;


-- QUERY 7 : SHOW ALL ORDERS WHERE QUANTITY IS GREATER THAN 1

SELECT
	*
FROM
	ORDERS
WHERE
	QUANTITY > 1;


-- QUERY 8 : RETRIEVE ORDERS WHERE TOTAL AMOUNT EXCEEDS $20

SELECT
	*
FROM
	ORDERS
WHERE
	TOTAL_AMOUNT > 20;


-- QUERY 9 : LIST ALL AVAILABLE BOOK GENRES

SELECT DISTINCT
	GENRE
FROM
	BOOKS;


-- QUERY 10 : FIND THE BOOK WITH THE LOWEST STOCK

SELECT
	*
FROM
	BOOKS
WHERE
	STOCK = (
		SELECT
			MIN(STOCK)
		FROM
			BOOKS
	);
/*==============================================================================
SECTION 4 : INTERMEDIATE SQL QUERIES
==============================================================================*/


-- QUERY 11 : CALCULATE THE TOTAL REVENUE GENERATED FROM ALL ORDERS

SELECT
	SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM
	ORDERS;


-- QUERY 12 : RETRIEVE THE TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE

SELECT
	B.GENRE,
	SUM(O.QUANTITY)
FROM
	ORDERS O
	JOIN BOOKS B
		ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.GENRE;


-- QUERY 13 : FIND THE AVERAGE PRICE OF BOOKS IN THE FANTASY GENRE

SELECT
	AVG(PRICE) AS AVERAGE_PRICE
FROM
	BOOKS
WHERE
	GENRE = 'Fantasy';


-- QUERY 14 : LIST CUSTOMERS WHO HAVE PLACED AT LEAST 2 ORDERS

SELECT
	C.CUSTOMER_ID,
	C.NAME,
	COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM
	ORDERS O
	JOIN CUSTOMERS C
		ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
	C.CUSTOMER_ID,
	C.NAME
HAVING
	COUNT(O.ORDER_ID) >= 2
ORDER BY
	ORDER_COUNT ASC;


-- QUERY 15 : FIND THE MOST FREQUENTLY ORDERED BOOK WITH CUSTOMER NAMES

SELECT
	C.NAME,
	B.TITLE,
	O.BOOK_ID,
	COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM
	ORDERS O
	JOIN CUSTOMERS C
		ON O.CUSTOMER_ID = C.CUSTOMER_ID
	JOIN BOOKS B
		ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	O.BOOK_ID,
	B.TITLE,
	C.NAME
ORDER BY
	ORDER_COUNT DESC;


-- QUERY 16 : FIND THE MOST FREQUENTLY ORDERED BOOK

SELECT
	B.TITLE,
	O.BOOK_ID,
	COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM
	ORDERS O
	JOIN BOOKS B
		ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	O.BOOK_ID,
	B.TITLE
ORDER BY
	ORDER_COUNT DESC;


-- QUERY 17 : SHOW THE TOP 3 MOST EXPENSIVE FANTASY BOOKS

SELECT
	B.TITLE,
	B.GENRE,
	B.PRICE AS EXPENSIVE_BOOKS
FROM
	BOOKS B
WHERE
	B.GENRE = 'Fantasy'
ORDER BY
	B.PRICE DESC
LIMIT
	3;


-- QUERY 18 : RETRIEVE THE TOTAL QUANTITY SOLD BY EACH AUTHOR

SELECT
	B.TITLE,
	B.AUTHOR,
	SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM
	ORDERS O
	JOIN BOOKS B
		ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	B.AUTHOR,
	B.TITLE
ORDER BY
	TOTAL_QUANTITY DESC;


-- QUERY 19 : LIST THE CITIES WHERE CUSTOMERS WHO SPENT OVER $30 ARE LOCATED

SELECT
	C.CITY,
	COUNT(*) AS LIST_CITIES
FROM
	ORDERS O
	JOIN CUSTOMERS C
		ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	O.TOTAL_AMOUNT > 30
GROUP BY
	C.CITY;


-- QUERY 20 : FIND THE CUSTOMER WHO SPENT THE MOST ON ORDERS

SELECT
	C.NAME,
	C.CUSTOMER_ID,
	SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM
	ORDERS O
	JOIN CUSTOMERS C
		ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY
	C.CUSTOMER_ID,
	C.NAME
ORDER BY
	TOTAL_SPENT DESC
LIMIT
	1;


-- QUERY 21 : CALCULATE THE STOCK REMAINING AFTER FULFILLING ALL ORDERS

SELECT
	B.BOOK_ID,
	B.TITLE,
	B.STOCK,
	COALESCE(SUM(O.QUANTITY), 0) AS ORDER_QUANTITY,
	B.STOCK - COALESCE(SUM(O.QUANTITY), 0) AS REMAINING_QUANTITY
FROM
	BOOKS B
	LEFT JOIN ORDERS O
		ON B.BOOK_ID = O.BOOK_ID
GROUP BY
	B.BOOK_ID,
	B.TITLE,
	B.STOCK
ORDER BY
	B.BOOK_ID;
/*==============================================================================
SECTION 5 : ADVANCED SQL QUERIES
==============================================================================*/


-- QUERY 22 : FIND ALL BOOKS THAT HAVE NEVER BEEN ORDERED

SELECT
	B.BOOK_ID,
	B.TITLE,
	B.AUTHOR,
	B.GENRE,
	B.STOCK
FROM
	BOOKS B
	LEFT JOIN ORDERS O
		ON B.BOOK_ID = O.BOOK_ID
WHERE
	O.ORDER_ID IS NULL;


-- QUERY 23 : FIND ALL CUSTOMERS WHO HAVE NEVER PLACED AN ORDER

SELECT
	C.CUSTOMER_ID,
	C.NAME,
	C.EMAIL,
	C.CITY,
	C.COUNTRY
FROM
	CUSTOMERS C
	LEFT JOIN ORDERS O
		ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE
	O.ORDER_ID IS NULL;


-- QUERY 24 : FIND THE TOP 5 BEST-SELLING BOOKS

SELECT
	B.BOOK_ID,
	B.TITLE,
	SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD
FROM
	ORDERS O
	JOIN BOOKS B
		ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	B.BOOK_ID,
	B.TITLE
ORDER BY
	TOTAL_BOOKS_SOLD DESC
LIMIT
	5;


-- QUERY 25 : FIND THE TOP 5 AUTHORS BASED ON BOOKS SOLD

SELECT
	B.AUTHOR,
	SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD
FROM
	ORDERS O
	JOIN BOOKS B
		ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	B.AUTHOR
ORDER BY
	TOTAL_BOOKS_SOLD DESC
LIMIT
	5;


-- QUERY 26 : RANK CUSTOMERS BASED ON THEIR TOTAL SPENDING

SELECT
	C.CUSTOMER_ID,
	C.NAME,
	SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT,
	RANK() OVER(
		ORDER BY SUM(O.TOTAL_AMOUNT) DESC
	) AS CUSTOMER_RANK
FROM
	ORDERS O
	JOIN CUSTOMERS C
		ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
	C.CUSTOMER_ID,
	C.NAME;


-- QUERY 27 : DENSE RANK BOOKS BASED ON TOTAL REVENUE GENERATED

SELECT
	B.BOOK_ID,
	B.TITLE,
	SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,
	DENSE_RANK() OVER(
		ORDER BY SUM(O.TOTAL_AMOUNT) DESC
	) AS BOOK_RANK
FROM
	ORDERS O
	JOIN BOOKS B
		ON O.BOOK_ID = B.BOOK_ID
GROUP BY
	B.BOOK_ID,
	B.TITLE;


-- QUERY 28 : CALCULATE THE RUNNING TOTAL OF REVENUE

SELECT
	ORDER_DATE,
	SUM(TOTAL_AMOUNT) AS DAILY_REVENUE,
	SUM(SUM(TOTAL_AMOUNT)) OVER(
		ORDER BY ORDER_DATE
	) AS RUNNING_REVENUE
FROM
	ORDERS
GROUP BY
	ORDER_DATE
ORDER BY
	ORDER_DATE;


-- QUERY 29 : SHOW THE PREVIOUS ORDER AMOUNT FOR EACH CUSTOMER

SELECT
	C.CUSTOMER_ID,
	C.NAME,
	O.ORDER_DATE,
	O.TOTAL_AMOUNT,
	LAG(O.TOTAL_AMOUNT) OVER(
		PARTITION BY C.CUSTOMER_ID
		ORDER BY O.ORDER_DATE
	) AS PREVIOUS_ORDER_AMOUNT
FROM
	ORDERS O
	JOIN CUSTOMERS C
		ON O.CUSTOMER_ID = C.CUSTOMER_ID;


-- QUERY 30 : FIND THE HIGHEST REVENUE GENERATING BOOK FROM EACH GENRE

WITH BOOK_REVENUE AS (

	SELECT
		B.GENRE,
		B.TITLE,
		SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE,

		ROW_NUMBER() OVER(
			PARTITION BY B.GENRE
			ORDER BY SUM(O.TOTAL_AMOUNT) DESC
		) AS RN

	FROM
		ORDERS O
		JOIN BOOKS B
			ON O.BOOK_ID = B.BOOK_ID

	GROUP BY
		B.GENRE,
		B.TITLE

)

SELECT
	GENRE,
	TITLE,
	TOTAL_REVENUE
FROM
	BOOK_REVENUE
WHERE
	RN = 1;
